### ISSUE TITLE
IoT thingspeak and v2

### ISSUE THREAD

**Issue by Steph77** [Tinkertanker/pxt-iot-environment-kit#10]
Hi,
I would like to use your ESP8266 module and his microbit associate's package : http://www.elecfreaks.com/store/blog/post/how-to-send-microbit-data-to-iot-platform.html

It seems that it doesn't work with makecode V2. 

Thanks
Regards

**Comment by elecfreaks** [comment]
@Steph77 https://www.elecfreaks.com/learn-en/how_to_use_thinkspeak/
