### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [tinkertanker/pxt-iot-environment-kit#34]
Hi @tinkertanker,

As you might have seen from https://github.com/microsoft/pxt-microbit/issues/3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer. 

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (https://github.com/lancaster-university/codal-microbit-v2/issues/31).

Looking at your extension source I believe that your extension falls under this category:

> 1. Use of mbed APIs that are in the compatibility layer, but no inclusion of mbed.h

**Comment by elecfreaks1** [comment]
@microbit-sam Can you confirm that the problem has been solved? In v4.2.1.

**Comment by lionyhw** [comment]
@microbit-sam  Can you confirm that the problem has been solved? In v4.2.1.

Sometimes, the E927 error is displayed.

**Comment by microbit-sam** [comment]
Yes, this should now compile and run on a V2

E927 indicates that the extensions is currently disabled on V2 by MakeCode, to reanable this you will need to submit a PR to MakeCode that updates the version number to v4.2.1

And example of the PR can be found here:
https://github.com/microsoft/pxt-microbit/pull/3769/files
