### ISSUE TITLE
Package add gives 'network request fails'

### ISSUE THREAD

**Issue by microbit-mark** [Tinkertanker/pxt-iot-environment-kit#5]
Trying to add the package results in a message that the 'network request failed'

![screen shot 2018-04-30 at 14 17 28](https://user-images.githubusercontent.com/31242877/39428980-4c01a104-4c81-11e8-97fc-48f237bf8128.png)

**Comment by firemansamm** [comment]
Odd that it says that it can't get it because of a 502 when other packages are working fine.

Thanks for the report, I'll look into it right now.

**Comment by firemansamm** [comment]
... I touched the environment.ts file and it went away. Odd, once again.

Can you verify it's been fixed now?

**Comment by microbit-mark** [comment]
Fixed
