### ISSUE TITLE
DHT11 temperature function NOT work after makecode update

### ISSUE THREAD

**Issue by yanyan11carol** [Tinkertanker/pxt-iot-environment-kit#8]
We have been fine using the read DHT11 function in the old makecode interface.
But after makecode update, the function does not work anymore.

Please check.
Thanks a lot!!!

**Comment by jandes** [comment]
````i experienced the same:  the DHT11 block works fine in the old make code editor and shows erroneous output in the new make code editor.  Is there a solution?

**Comment by yjsoon** [comment]
Should be fixed with #9. Thanks all

**Comment by jandes** [comment]
Hi YJ Soon,
Thank you very much!
When is the new package addable as blocks in the micro:bit environment?

Have a nice day,
Jan

**Comment by yjsoon** [comment]
@jandes It should have been working but we seem to have run into an issue with the latest version, We'll be on it soon as we can.
